name: run main.py

on:
  schedule:
    - cron: '10 * * * *' # At 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          bearer_token: ${{secrets.BEARER_TOKEN}}
          api_key: ${{secrets.API_KEY}}
          api_key_secret: ${{secrets.API_KEY_SECRET}}
          access_token: ${{secrets.ACCESS_TOKEN}}
          access_token_secret: ${{secrets.ACCESS_TOKEN_SECRET}}
          rapid_api_key: ${{secrets.RAPIDAPIKEY}}
        run: |
          python tennisbot.py
          git config user.email "bawejahritik@gmail.com"
          git config user.name "Hritik Baweja"
          git add .
          git commit -m "update matchIds"
          git push
